Q1


In [125]:
import numpy as np
import pandas as pd

In [126]:
df = pd.read_csv('/content/drive/MyDrive/ML_Lab/iris_csv.csv')


In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   sepallength  150 non-null    float64
 1   sepalwidth   150 non-null    float64
 2   petallength  150 non-null    float64
 3   petalwidth   150 non-null    float64
 4   class        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [128]:
df.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [129]:
df.iloc[:,4].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [130]:
df.isna().sum()

sepallength    0
sepalwidth     0
petallength    0
petalwidth     0
class          0
dtype: int64

In [131]:
df_setosa = df.copy()
df_versicolor = df.copy()
df_virginica = df.copy()
datasets = [df_setosa, df_versicolor, df_virginica]

In [132]:
classes = ["Iris-setosa","Iris-versicolor","Iris-virginica"]
m = len(df)

for i in range(3):
  for j in range(m):
    if datasets[i].iloc[j,4] == classes[i]:
      datasets[i].iloc[j,4] = 1
    else:
      datasets[i].iloc[j,4] = 0

In [133]:
df

sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [134]:
datasets[1].iloc[:,4].value_counts()

0    100
1     50
Name: class, dtype: int64

In [135]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
data_split = {}
for i in range(3):
  x = datasets[i].iloc[:,:4]
  y = datasets[i].iloc[:,4]
  scaler = StandardScaler()
  x_scaled = scaler.fit_transform(x)
  x_scaled = np.insert(x_scaled,0,values=1,axis=1)
  x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size=0.3,random_state=42)
  data_split[classes[i]] = [x_train,x_test,y_train,y_test]

In [136]:
data_split[classes[0]][0]

array([[ 1.00000000e+00, -4.16009689e-01, -1.51337539e+00,
        -3.33612130e-02, -2.61192967e-01],
       [ 1.00000000e+00,  5.53333275e-01, -5.87763531e-01,
         7.62758643e-01,  3.96171883e-01],
       [ 1.00000000e+00,  6.74501145e-01,  1.06445364e-01,
         9.90221459e-01,  7.90590793e-01],
       [ 1.00000000e+00,  9.16836886e-01, -1.24957601e-01,
         3.64698715e-01,  2.64698913e-01],
       [ 1.00000000e+00,  1.64384411e+00,  1.26346019e+00,
         1.33141568e+00,  1.71090158e+00],
       [ 1.00000000e+00, -1.73673948e-01, -3.56360566e-01,
         2.50967307e-01,  1.33225943e-01],
       [ 1.00000000e+00,  2.12851559e+00, -1.24957601e-01,
         1.61574420e+00,  1.18500970e+00],
       [ 1.00000000e+00, -2.94841818e-01, -1.24957601e-01,
         4.21564419e-01,  3.96171883e-01],
       [ 1.00000000e+00, -9.00681170e-01,  1.03205722e+00,
        -1.34127240e+00, -1.31297673e+00],
       [ 1.00000000e+00,  2.24968346e+00, -5.87763531e-01,
         1.67260991e+00

In [137]:
betas = []
for i in range(3):
  n = 1000
  alpha = 0.01
  m,k = data_split[classes[i]][0].shape
  beta = np.zeros(k)
  for j in range(n):
    cost_gradient = np.zeros(k)
    z = data_split[classes[i]][0].dot(beta)
    predicted = 1/(1+np.exp(-z))
    difference = predicted - data_split[classes[i]][2]
    for l in range(k):
      cost_gradient[l] = np.sum(difference.dot(data_split[classes[i]][0][:,l]))
    for l in range(k):
      beta[l] = beta[l] - (alpha/m)*cost_gradient[l]
  betas.append(beta)
print(betas)

[array([-0.8558931 , -0.6134613 ,  0.92596984, -1.04971059, -0.97348642]), array([-0.6921732 , -0.01674772, -0.98045542,  0.1583929 , -0.11211971]), array([-0.86376588,  0.57274881,  0.23536641,  0.79180772,  1.01087805])]


In [138]:
for i in range(3):
  x_train = data_split[classes[i]][1]
  y_predict = 1/(1+np.exp(-(x_train.dot(betas[i]))))
  y_label = np.zeros(len(y_predict))
  for j in range(len(y_predict)):
    if(y_predict[j]>=0.5):
      y_label[j]=1
  data_split[classes[i]].append(y_label)
  

data_split[classes[0]][4]


array([0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1.])

In [139]:
accuracies = []
for i in range(3):
  y_test = data_split[classes[i]][3]
  y_label = data_split[classes[i]][4]

  y_test = np.array(y_test).reshape(-1,1)
  tp = 0
  tn = 0
  fp = 0
  fn = 0

  for j in range(len(y_label)):
    if(y_test[j] ==1 and y_label[j]==1):
      tp = tp+1
    elif(y_test[j]==1 and y_label[j]==0):
      fn = fn+1
    elif(y_test[j]==0 and y_label[j]==0):
      tn = tn+1
    elif(y_test[j]==0 and y_label[j]==1):
      fp = fp+1
  accuracy = (tp+tn)/(tp+tn+fp+fn)
  print(accuracy)
  accuracies.append(accuracy)

1.0
0.6888888888888889
0.8666666666666667


In [140]:
inputs = df.iloc[:,:4]
outputs = df.iloc[:,4]
accuratepredicts = 0
inputs_scaled = scaler.fit_transform(inputs)
inputs_scaled = np.insert(inputs_scaled,0,values=1,axis=1)

for i in range(len(inputs_scaled)):
  prob = []
  for j in range(3):
    z = inputs_scaled[i,:].dot(betas[j])
    hypo = 1/(1+np.exp(-z))
    prob.append(hypo)
  
  predict = prob.index(max(prob))
  
  if(outputs[i]== classes[predict]):
    accuratepredicts += 1
print(accuratepredicts)
accuracy = (accuratepredicts/150)*100
print(accuracy)

125
83.33333333333334


Q2 part 1

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_table('/content/drive/MyDrive/ML_Lab/exam6.txt',sep=",",header=None)
df.head()

0        1  2
0  0.051267  0.69956  1
1 -0.092742  0.68494  1
2 -0.213710  0.69225  1
3 -0.375000  0.50219  1
4 -0.513250  0.46564  1

In [6]:
df.isna().sum()

0    0
1    0
2    0
dtype: int64

In [8]:
from sklearn.preprocessing import StandardScaler
x = df.iloc[:,:2]
y = df.iloc[:,2]
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_scaled = np.insert(x_scaled,0,values=1,axis=1)

x_scaled.shape

(118, 3)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size=0.3,random_state=42)
x_train.shape

(82, 3)

In [15]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 6, interaction_only=False, include_bias=False)
x_train = poly.fit_transform(x_train)
x_test = poly.fit_transform(x_test)

In [16]:
n = 1000
alpha = 10
m,k = x_train.shape
beta = np.zeros(k)
for i in range(n):
    cost_gradient = np.zeros(k)
    z = x_train.dot(beta)
    predicted = 1/(1+np.exp(-z))
    difference = predicted - y_train
    for j in range(k):
        cost_gradient[j] = np.sum(difference.dot(x_train[:,j]))
    for j in range(k):
        beta[j] = beta[j] - (alpha/m)*cost_gradient[j]
print(beta)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


[  0.28072924  -3.59443672   0.77039761   0.28072924  -3.59443672
   0.77039761  -1.86237737  -0.0735327    4.31773641   0.28072924
  -3.59443672   0.77039761  -1.86237737  -0.0735327    4.31773641
   3.61031171  13.32989994   1.06291757  -3.65256312   0.28072924
  -3.59443672   0.77039761  -1.86237737  -0.0735327    4.31773641
   3.61031171  13.32989994   1.06291757  -3.65256312  16.03431259
  -2.2554008   -7.63288276  -2.78798506   1.03780114   0.28072924
  -3.59443672   0.77039761  -1.86237737  -0.0735327    4.31773641
   3.61031171  13.32989994   1.06291757  -3.65256312  16.03431259
  -2.2554008   -7.63288276  -2.78798506   1.03780114  -1.85312342
  -7.44662275   3.99239177 -11.88438672  -3.81810431   6.25498723
   0.28072924  -3.59443672   0.77039761  -1.86237737  -0.0735327
   4.31773641   3.61031171  13.32989994   1.06291757  -3.65256312
  16.03431259  -2.2554008   -7.63288276  -2.78798506   1.03780114
  -1.85312342  -7.44662275   3.99239177 -11.88438672  -3.81810431
   6.254987

In [17]:
y_pred = 1/(1+np.exp(-(x_test.dot(beta))))
y_label = np.zeros(len(y_pred))
for i in range(len(y_pred)):
    if(y_pred[i]>=0.5):
        y_label[i]=1
y_label

array([1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
       1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1.,
       0., 0.])

In [18]:
tp = 0
tn = 0
fp = 0
fn = 0
y_test = np.array(y_test).reshape(-1,1)
for i in range(len(y_label)):
    if(y_test[i]==1 and y_label[i]==1):
        tp+=1
    if(y_test[i]==1 and y_label[i]==0):
        fn+=1
    if(y_test[i]==0 and y_label[i]==0):
        tn+=1
    if(y_test[i]==0 and y_label[i]==1):
        fp+=1
print("True Positive = ", tp)
print("True Negative = ", tn)
print("False Positive = ", fp)
print("False Negative = ", fn)
accuracy=(tp+tn)/(tp+tn+fp+fn)
print("Accuracy : ",accuracy)

True Positive =  11
True Negative =  14
False Positive =  2
False Negative =  9
Accuracy :  0.6944444444444444


In [19]:
precision_pos = tp/(tp+fp)
recall_pos = tp/(tp+fn)
f1_score_pos = 2*precision_pos*recall_pos/(precision_pos+recall_pos)

precision_neg = tn/(tn+fn)
recall_neg = tn/(tn+fp)
f1_score_neg = 2*precision_neg*recall_neg/(precision_neg+recall_neg)
print("Precision Positive = ", precision_pos)
print("Recall Positive = ", recall_pos)
print("F1_Score Positive = ", f1_score_pos)
print("Precision Negative = ", precision_neg)
print("Recall Negative = ", recall_neg)
print("F1_Score Negative = ", f1_score_pos)

Precision Positive =  0.8461538461538461
Recall Positive =  0.55
F1_Score Positive =  0.6666666666666667
Precision Negative =  0.6086956521739131
Recall Negative =  0.875
F1_Score Negative =  0.6666666666666667


In [20]:
macro_precision = (precision_pos + precision_neg)/2
macro_recall = (recall_pos + recall_neg)/2
macro_f1_score = (f1_score_pos + f1_score_neg)/2
print("Macro Precision = ", macro_precision)
print("Macro Recall = ", macro_recall)
print("Macro F1_Score = ", macro_f1_score)

Macro Precision =  0.7274247491638797
Macro Recall =  0.7125
Macro F1_Score =  0.6923076923076923


Q2 part 2

In [21]:
lambda_val = 0.2
A = x_train.T.dot(x_train)
I = np.identity(A.shape[0])
B = A + lambda_val * I
C = np.linalg.inv(B)
D = C.dot(x_train.T)
beta = D.dot(y_train)

In [22]:
n = 1000
alpha = 10
m,k = x_train.shape
for i in range(n):
    cost_gradient = np.zeros(k)
    z = x_train.dot(beta)
    predicted = 1/(1+np.exp(-z))
    difference = predicted - y_train
    for j in range(k):
        cost_gradient[j] = np.sum(difference.dot(x_train[:,j]))
    for j in range(k):
        beta[j] = beta[j] - (alpha/m)*cost_gradient[j]
print(beta)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: overflow encountered in exp
  import sys


[  1.80545544  -2.39563398  -0.41599118   1.80545544  -2.39563398
  -0.41599118  -0.4090932   -0.46311724   6.06522759   1.80545544
  -2.39563398  -0.41599118  -0.4090932   -0.46311724   6.06522759
   4.91551045  12.42416606   1.3731632   -4.94668349   1.80545544
  -2.39563398  -0.41599118  -0.4090932   -0.46311724   6.06522759
   4.91551045  12.42416606   1.3731632   -4.94668349  16.85901742
  -2.92235285  -6.4492812   -3.09396815   3.23794329   1.80545544
  -2.39563398  -0.41599118  -0.4090932   -0.46311724   6.06522759
   4.91551045  12.42416606   1.3731632   -4.94668349  16.85901742
  -2.92235285  -6.4492812   -3.09396815   3.23794329  -1.29792627
  -7.1979337    3.41819634 -11.69359872  -3.53381239   3.10430577
   1.80545544  -2.39563398  -0.41599118  -0.4090932   -0.46311724
   6.06522759   4.91551045  12.42416606   1.3731632   -4.94668349
  16.85901742  -2.92235285  -6.4492812   -3.09396815   3.23794329
  -1.29792627  -7.1979337    3.41819634 -11.69359872  -3.53381239
   3.10430

In [23]:
y_pred = 1/(1+np.exp(-(x_test.dot(beta))))
y_label = np.zeros(len(y_pred))
for i in range(len(y_pred)):
    if(y_pred[i]>=0.5):
        y_label[i]=1
y_label

array([1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1.,
       1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 0.])

In [24]:
tp = 0
tn = 0
fp = 0
fn = 0
y_test = np.array(y_test).reshape(-1,1)
for i in range(len(y_label)):
    if(y_test[i]==1 and y_label[i]==1):
        tp+=1
    if(y_test[i]==1 and y_label[i]==0):
        fn+=1
    if(y_test[i]==0 and y_label[i]==0):
        tn+=1
    if(y_test[i]==0 and y_label[i]==1):
        fp+=1
print("True Positive = ", tp)
print("True Negative = ", tn)
print("False Positive = ", fp)
print("False Negative = ", fn)
accuracy=(tp+tn)/(tp+tn+fp+fn)
print("Accuracy : ",accuracy)

True Positive =  19
True Negative =  11
False Positive =  5
False Negative =  1
Accuracy :  0.8333333333333334


In [25]:
precision_pos = tp/(tp+fp)
recall_pos = tp/(tp+fn)
f1_score_pos = 2*precision_pos*recall_pos/(precision_pos+recall_pos)

precision_neg = tn/(tn+fn)
recall_neg = tn/(tn+fp)
f1_score_neg = 2*precision_neg*recall_neg/(precision_neg+recall_neg)
print("Precision Positive = ", precision_pos)
print("Recall Positive = ", recall_pos)
print("F1_Score Positive = ", f1_score_pos)
print("Precision Negative = ", precision_neg)
print("Recall Negative = ", recall_neg)
print("F1_Score Negative = ", f1_score_pos)

Precision Positive =  0.7916666666666666
Recall Positive =  0.95
F1_Score Positive =  0.8636363636363635
Precision Negative =  0.9166666666666666
Recall Negative =  0.6875
F1_Score Negative =  0.8636363636363635


In [26]:
macro_precision = (precision_pos + precision_neg)/2
macro_recall = (recall_pos + recall_neg)/2
macro_f1_score = (f1_score_pos + f1_score_neg)/2
print("Macro Precision = ", macro_precision)
print("Macro Recall = ", macro_recall)
print("Macro F1_Score = ", macro_f1_score)

Macro Precision =  0.8541666666666666
Macro Recall =  0.81875
Macro F1_Score =  0.8246753246753247
